apiVersion: v1
kind: Service
metadata:
  name: gim-web-service
spec:
  selector:
    app: gim-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposing to the outside world, replace with NodePort if needed

# Add to your frontend service or create analytics service
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP