# k8s/test-jobs/frontend-integration-test.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-integration-test
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: integration-test
        image: node:18-alpine
        command: ["sh", "-c"]
        args:
        - |
          npm install -g axios jest
          cat > /tmp/frontend-test.js << 'EOF'
          const axios = require('axios');
          
          describe('Frontend Integration Tests', () => {
            test('Frontend health check', async () => {
              const response = await axios.get('http://frontend-service.default.svc.cluster.local/health');
              expect(response.status).toBe(200);
            });
            
            test('ClickHouse connectivity', async () => {
              // Test analytics tracking
              const analyticsData = {
                event_type: 'page_view',
                page_url: '/test',
                user_id: 'test-user',
                session_id: 'test-session'
              };
              
              const response = await axios.post(
                'http://analytics-service.default.svc.cluster.local:3002/api/analytics/track',
                analyticsData
              );
              expect(response.status).toBe(200);
            });
          });
          EOF
          
          cd /tmp && npm test frontend-test.js
      backoffLimit: 2